name: Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        build:
        - name: 'byte90'
          command: |
            idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.byte90" build
        - name: 'ws-s3-touch'
          command: |
            idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.ws-s3-touch" build

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build main
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v5.4
        target: esp32s3
        path: '.'
        command: ${{ matrix.build.command }}
