name: Build and Package Main

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

env:
  IDF_TARGET: 'esp32s3'
  IDF_VERSION: 'v5.5.1'
  IDF_COMPONENT_MANAGER: "1" # whether to enable the component manager or not
  FLASH_TOTAL_OVERRIDE: '2097152' # 2MB flash app partition for hachi

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      matrix:
        build:
        - name: 'byte90'
          command: |
            idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.byte90" build
        - name: 'ws-s3-touch'
          command: |
            idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.ws-s3-touch" build

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build Main Code
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ env.IDF_VERSION }}
        target: ${{ env.IDF_TARGET }}
        path: '.'
        command: ${{ matrix.build.command }}

    - name: Upload Build Outputs
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.build.name}}-build-artifacts
        path: |
          build/*.bin
          build/*.elf
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/flasher_args.json
          build/flash_args

    - name: Zip up build files for release using matrix build name + release tag name
      if: ${{ github.event.release && github.event.action == 'published' }}
      shell: bash
      run: |
        # zip up just the files we uploaded for the release
        zip_name="mini-retro-computer-${{ matrix.build.name }}_$(git describe --tags --dirty).zip"
        zip -r -j $zip_name build/*.bin build/*.elf build/bootloader/bootloader.bin build/partition_table/partition-table.bin build/flasher_args.json build/flash_args
        echo "artifact_path=$zip_name" >> "$GITHUB_ENV"

    - name: Attach files to release
      uses: softprops/action-gh-release@v2
      if: ${{ github.event.release && github.event.action == 'published' }}
      with:
        files: ${{ env.artifact_path }}

    - name: Determine Size Delta
      # only run this on the byte90 build and if the release is published
      if: ${{ github.event.release && github.event.action == 'published' && matrix.build.name == 'byte90' }}
      uses: esp-cpp/esp-idf-size-delta@v1
      with:
        app_name: "Mini Retro Computer"
        app_path: "."
        idf_target: ${{ env.IDF_TARGET }}
        idf_version: ${{ env.IDF_VERSION }}
        idf_component_manager: ${{ env.IDF_COMPONENT_MANAGER }}
        flash_total_override: ${{ env.FLASH_TOTAL_OVERRIDE }}
        post_comment: 'false'

  package:
    name: Package the binaries into an executables for Windows, MacOS, and Linux (Ubuntu)
    needs: build
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build:
          - name: 'byte90'
          - name: 'ws-s3-touch'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: esp-cpp/esp-packaged-programmer-action@v1.0.5
        with:
          zipfile-name: '${{ matrix.build.name }}-build-artifacts'
          programmer-name: 'mini-retro-computer-${{ matrix.build.name }}_programmer'
